image:
  file: .gitpod.Dockerfile

ports:
  # Laravel server
  - port: 8000
    onOpen: open-preview
  # MySQL server
  - port: 3306
    onOpen: ignore

tasks:
  - init: >
      mysql -u root -e "create database homestead" &&
      cp .env.example .env &&
      sed -i "s|APP_URL=http://localhost|APP_URL=${GITPOD_WORKSPACE_URL}|g" .env &&
      sed -i "s|APP_URL=https://|APP_URL=https://8000-|g" .env &&
      sed -i "s|DB_USERNAME=homestead|DB_USERNAME=root|g" .env &&
      sed -i "s|DB_PASSWORD=secret|DB_PASSWORD=|g" .env &&
      composer install --ignore-platform-reqs &&
      npm i &&
      php artisan key:generate &&
      php artisan migrate
  - command: >
      php -S 0.0.0.0:8000 -t public
    name: PHP Web Server
  - command: >
      npm run dev      
    name: NPM run dev